/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить список встреч по всем типам событий
         * @description Страница предстоящих встреч.
         *
         *     Единый список бронирований по всем типам событий, отсортированный по
         *     времени начала по возрастанию. По умолчанию возвращаются только встречи,
         *     которые ещё не начались (`scope=upcoming`).
         */
        get: operations["Admin_listBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить список типов событий
         * @description Список типов событий владельца, отсортированный по `createdAt` по убыванию.
         */
        get: operations["Admin_listEventTypes"];
        put?: never;
        /**
         * Создать тип события
         * @description Создание типа события.
         *
         *     Владелец задаёт `id`, название, описание и длительность в минутах.
         *     Длительность определяет длину слота для гостя.
         */
        post: operations["Admin_createEventType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить профиль владельца календаря
         * @description Профиль владельца календаря.
         *
         *     Возвращает заранее заданный профиль, который по умолчанию используется в
         *     административной части: его часовой пояс, рабочие часы, шаг сетки слотов и
         *     глубину окна записи.
         */
        get: operations["Admin_getOwner"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{bookingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить бронирование
         * @description Страница подтверждения: детали созданного бронирования.
         */
        get: operations["Public_getBooking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить список видов брони
         * @description Страница видов брони.
         *
         *     Возвращает все типы событий владельца с названием, описанием и
         *     длительностью, чтобы гость мог выбрать нужный вид встречи.
         */
        get: operations["Public_listEventTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{eventTypeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить тип события
         * @description Карточка выбранного типа события перед открытием календаря.
         */
        get: operations["Public_getEventType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{eventTypeId}/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Создать бронирование на свободный слот
         * @description Создание бронирования на выбранный слот.
         *
         *     Гость передаёт только время начала и свои контакты — время окончания
         *     сервер вычисляет по длительности типа события.
         *
         *     Ошибки:
         *     - `400 SLOT_OUT_OF_WINDOW` — время вне окна `[сейчас; сейчас + 14 дней)`;
         *     - `400 SLOT_NOT_ALIGNED` — время не на сетке слотов или встреча не
         *     укладывается в рабочие часы владельца;
         *     - `400 VALIDATION_ERROR` — некорректные данные гостя;
         *     - `404 EVENT_TYPE_NOT_FOUND` — тип события не существует;
         *     - `409 SLOT_TAKEN` — время уже занято другой записью, в том числе записью
         *     другого типа события.
         */
        post: operations["Public_createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{eventTypeId}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить свободные слоты на окно записи
         * @description Календарь свободных слотов выбранного типа события.
         *
         *     Слоты формируются на окно записи `[from; to)`, по умолчанию — на
         *     `Owner.bookingWindowDays` (14) дней, начиная с текущего момента.
         *     Внутри окна берутся только интервалы, кратные `Owner.slotStepMinutes`,
         *     целиком укладывающиеся в `Owner.workingHours` и не пересекающиеся ни с
         *     одним существующим бронированием календаря — включая брони других типов
         *     событий.
         *
         *     Ошибки: `400 SLOT_OUT_OF_WINDOW`, если `from`/`to` выходят за окно записи
         *     или `to` не больше `from`; `404 EVENT_TYPE_NOT_FOUND`.
         */
        get: operations["Public_listSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Стандартное тело ошибки. */
        ApiError: {
            /** @description Машиночитаемый код ошибки. */
            code: components["schemas"]["ErrorCode"];
            /** @description Человекочитаемое описание проблемы. */
            message: string;
            /** @description Дополнительный контекст ошибки (например, имя невалидного поля). */
            details?: Record<string, never>;
        };
        /** @description Бронирование слота гостем. */
        Booking: {
            /** @description Идентификатор бронирования. */
            id: string;
            /** @description Тип события, на который создана бронь. */
            eventTypeId: string;
            /** @description Название типа события на момент бронирования. */
            eventTypeTitle: string;
            /**
             * Format: date-time
             * @description Начало встречи.
             */
            start: string;
            /**
             * Format: date-time
             * @description Окончание встречи: `start + EventType.durationMinutes`, считает сервер.
             */
            end: string;
            /** @description Данные гостя. */
            guest: components["schemas"]["Guest"];
            /**
             * Format: date-time
             * @description Момент создания бронирования.
             */
            createdAt: string;
        };
        /** @description Данные для создания бронирования гостем. */
        BookingCreate: {
            /**
             * Format: date-time
             * @description Начало выбранного слота. Должно совпадать со `start` свободного слота из
             *     `GET /event-types/{eventTypeId}/slots`. Время окончания вычисляет сервер.
             */
            start: string;
            /** @description Данные гостя. */
            guest: components["schemas"]["Guest"];
        };
        /**
         * @description Какие встречи включать в список владельца.
         * @enum {string}
         */
        BookingScope: "upcoming" | "past" | "all";
        /** @description Слоты одного календарного дня в часовом поясе владельца. */
        DaySlots: {
            /**
             * Format: date
             * @description Дата дня в часовом поясе владельца.
             */
            date: string;
            /** @description Слоты этого дня. Пустой массив, если свободного времени нет. */
            slots: components["schemas"]["Slot"][];
        };
        /**
         * @description Машиночитаемый код ошибки домена.
         * @enum {string}
         */
        ErrorCode: "VALIDATION_ERROR" | "EVENT_TYPE_NOT_FOUND" | "EVENT_TYPE_ID_CONFLICT" | "BOOKING_NOT_FOUND" | "SLOT_TAKEN" | "SLOT_OUT_OF_WINDOW" | "SLOT_NOT_ALIGNED";
        /**
         * @description Тип события — вид встречи, который создаёт владелец и выбирает гость.
         *     Длительность типа события определяет длину слота и время окончания брони.
         */
        EventType: {
            /**
             * @description Идентификатор типа события, задаваемый владельцем при создании.
             *     Уникален и используется в публичных ссылках.
             */
            id: string;
            /** @description Название, которое видит гость на странице видов брони. */
            title: string;
            /** @description Описание встречи для гостя. */
            description: string;
            /**
             * Format: int32
             * @description Длительность встречи в минутах.
             */
            durationMinutes: number;
            /**
             * Format: date-time
             * @description Момент создания типа события.
             */
            readonly createdAt: string;
        };
        /** @description Данные для создания типа события владельцем. */
        EventTypeCreate: {
            /** @description Идентификатор типа события, задаётся владельцем. */
            id: string;
            /** @description Название типа события. */
            title: string;
            /** @description Описание типа события. */
            description: string;
            /**
             * Format: int32
             * @description Длительность встречи в минутах.
             */
            durationMinutes: number;
        };
        /** @description Гость, создающий бронирование. Аккаунт не создаётся. */
        Guest: {
            /** @description Имя гостя. */
            name: string;
            /**
             * Format: email
             * @description Email гостя для подтверждения встречи.
             */
            email: string;
            /** @description Необязательный комментарий к встрече. */
            notes?: string;
        };
        /**
         * @description Владелец календаря — единственный заранее заданный профиль.
         *     Регистрация и вход отсутствуют, поэтому профиль не создаётся через API,
         *     а только читается: он определяет календарь, в который попадают все брони.
         */
        Owner: {
            /** @description Идентификатор владельца. */
            readonly id: string;
            /** @description Отображаемое имя владельца. */
            name: string;
            /**
             * Format: email
             * @description Контактный email владельца.
             */
            email: string;
            /** @description Часовой пояс владельца; в нём трактуются `workingHours`. */
            timezone: components["schemas"]["Timezone"];
            /** @description Рабочие часы, внутри которых формируются слоты. */
            workingHours: components["schemas"]["WorkingHours"];
            /**
             * Format: int32
             * @description Шаг сетки слотов в минутах: допустимые значения начала встречи.
             * @default 30
             */
            slotStepMinutes: number;
            /**
             * Format: int32
             * @description Глубина окна записи в днях, начиная с текущей даты.
             * @default 14
             */
            bookingWindowDays: number;
        };
        /** @description Постраничный список. */
        PageBooking: {
            /** @description Элементы текущей страницы. */
            items: components["schemas"]["Booking"][];
            /**
             * Format: int32
             * @description Общее количество элементов, подходящих под фильтры.
             */
            total: number;
            /**
             * Format: int32
             * @description Размер страницы, использованный при выборке.
             */
            limit: number;
            /**
             * Format: int32
             * @description Смещение от начала выборки.
             */
            offset: number;
        };
        /** @description Постраничный список. */
        PageEventType: {
            /** @description Элементы текущей страницы. */
            items: components["schemas"]["EventType"][];
            /**
             * Format: int32
             * @description Общее количество элементов, подходящих под фильтры.
             */
            total: number;
            /**
             * Format: int32
             * @description Размер страницы, использованный при выборке.
             */
            limit: number;
            /**
             * Format: int32
             * @description Смещение от начала выборки.
             */
            offset: number;
        };
        /**
         * @description Слот — вычисляемый интервал в календаре владельца. Слоты не хранятся:
         *     они строятся с шагом `Owner.slotStepMinutes` внутри `Owner.workingHours`
         *     на длину `EventType.durationMinutes`.
         */
        Slot: {
            /**
             * Format: date-time
             * @description Начало слота.
             */
            start: string;
            /**
             * Format: date-time
             * @description Окончание слота: `start + EventType.durationMinutes`.
             */
            end: string;
            /**
             * @description Свободен ли слот. `false`, если слот пересекается с любым существующим
             *     бронированием календаря — независимо от его типа события.
             */
            isAvailable: boolean;
        };
        /** @description Календарь свободных слотов для выбранного типа события. */
        SlotsResponse: {
            /** @description Тип события, для которого построены слоты. */
            eventTypeId: string;
            /**
             * Format: int32
             * @description Длительность встречи, использованная при построении слотов.
             */
            durationMinutes: number;
            /** @description Часовой пояс владельца, в котором сгруппированы дни. */
            timezone: components["schemas"]["Timezone"];
            /**
             * Format: date-time
             * @description Начало окна записи (по умолчанию — текущий момент).
             */
            windowStart: string;
            /**
             * Format: date-time
             * @description Конец окна записи (по умолчанию — `windowStart + bookingWindowDays`).
             */
            windowEnd: string;
            /** @description Дни окна записи по возрастанию, включая дни без свободных слотов. */
            days: components["schemas"]["DaySlots"][];
        };
        /**
         * @description Часовой пояс в формате IANA, например `Europe/Moscow`.
         * @example Europe/Moscow
         */
        Timezone: string;
        /** @description Рабочие часы владельца внутри одного дня, в его часовом поясе. */
        WorkingHours: {
            /**
             * Format: time
             * @description Время начала приёма, например `10:00:00`.
             */
            start: string;
            /**
             * Format: time
             * @description Время окончания приёма, например `19:00:00`. Строго больше `start`.
             */
            end: string;
        };
    };
    responses: never;
    parameters: {
        /** @description Максимальное количество элементов в ответе. */
        "PaginationQuery.limit": number;
        /** @description Смещение от начала выборки. */
        "PaginationQuery.offset": number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Admin_listBookings: {
        parameters: {
            query?: {
                /** @description Какие встречи включать в выборку. */
                scope?: components["schemas"]["BookingScope"];
                /** @description Включать встречи, начинающиеся не раньше указанного момента. */
                from?: string;
                /** @description Включать встречи, начинающиеся раньше указанного момента. */
                to?: string;
                /** @description Необязательный фильтр по одному типу события. */
                eventTypeId?: string;
                /** @description Максимальное количество элементов в ответе. */
                limit?: components["parameters"]["PaginationQuery.limit"];
                /** @description Смещение от начала выборки. */
                offset?: components["parameters"]["PaginationQuery.offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageBooking"];
                };
            };
            /** @description Ответ с ошибкой и конкретным HTTP-статусом. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Admin_listEventTypes: {
        parameters: {
            query?: {
                /** @description Максимальное количество элементов в ответе. */
                limit?: components["parameters"]["PaginationQuery.limit"];
                /** @description Смещение от начала выборки. */
                offset?: components["parameters"]["PaginationQuery.offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageEventType"];
                };
            };
            /** @description Ответ с ошибкой и конкретным HTTP-статусом. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Admin_createEventType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Ответ с ошибкой и конкретным HTTP-статусом. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Ответ с ошибкой и конкретным HTTP-статусом. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Admin_getOwner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Owner"];
                };
            };
        };
    };
    Public_getBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор бронирования. */
                bookingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description Ответ с ошибкой и конкретным HTTP-статусом. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Public_listEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    Public_getEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор типа события. */
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Ответ с ошибкой и конкретным HTTP-статусом. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Public_createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор типа события. */
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description Ответ с ошибкой и конкретным HTTP-статусом. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Ответ с ошибкой и конкретным HTTP-статусом. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Ответ с ошибкой и конкретным HTTP-статусом. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Public_listSlots: {
        parameters: {
            query?: {
                /** @description Начало запрашиваемого окна. По умолчанию — текущий момент. */
                from?: string;
                /**
                 * @description Конец запрашиваемого окна. По умолчанию — `from + bookingWindowDays`
                 *     (14 дней). Не может выходить за границу окна записи.
                 */
                to?: string;
                /** @description Возвращать только свободные слоты. При `false` слоты приходят с `isAvailable`. */
                onlyAvailable?: boolean;
            };
            header?: never;
            path: {
                /** @description Идентификатор типа события. */
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotsResponse"];
                };
            };
            /** @description Ответ с ошибкой и конкретным HTTP-статусом. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Ответ с ошибкой и конкретным HTTP-статусом. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}

// Convenience type aliases
export type ApiError = components["schemas"]["ApiError"];
export type Booking = components["schemas"]["Booking"];
export type BookingCreate = components["schemas"]["BookingCreate"];
export type BookingScope = components["schemas"]["BookingScope"];
export type DaySlots = components["schemas"]["DaySlots"];
export type ErrorCode = components["schemas"]["ErrorCode"];
export type EventType = components["schemas"]["EventType"];
export type EventTypeCreate = components["schemas"]["EventTypeCreate"];
export type Guest = components["schemas"]["Guest"];
export type Owner = components["schemas"]["Owner"];
export type PageBooking = components["schemas"]["PageBooking"];
export type PageEventType = components["schemas"]["PageEventType"];
export type Slot = components["schemas"]["Slot"];
export type SlotsResponse = components["schemas"]["SlotsResponse"];
export type Timezone = components["schemas"]["Timezone"];
export type WorkingHours = components["schemas"]["WorkingHours"];
export type PaginationQuery = components["parameters"];
